version = 2

songs = [
    "chlebie_najcichszy.md",
    "niechaj_zstapi_duch_twoj.md",
    "otrzyjcie_juz_lzy.md",
    "zmartwychwstal_pan.md",
    "czytanie_maciek.md",
    "godzien.md",
    "chrystus_zmartwychwstan_jest.md",
    "jezus_zwyciezyl.md",
    "psalm_148.md",
    "baranki_mlode.md",
    "raduje_sie_dusza.md",
    "zwyciezca_smierci.md",
    "przychodzisz_panie.md",
    "matko_ktora_nas_znasz.md",
    "kantyk_mojzesza.md",

    "dodatkowe.md",
    "nasz_bog.md",
    "panie_gdy_tone.md",
    "zaufalem_panu.md",
]

notation = "english"

[[output]]
file = "songbook.pdf"
template = "pdf.hbs"

[[output]]
file = "songbook.html"

[book]
title = "Wielka Sobota 2025"
subtitle = "Adoracja"
chorus_label = "Ref"
title_note = "Lista pieśni na adorację w Wielką Sobotę ad 2025"
